<?php 
require "./../connect.php";
session_start();

$sql = "SELECT mp.*, p.promo_name, m.first_name, m.last_name FROM memberpromos AS mp
        JOIN promo AS p
        ON mp.promo_id = p.promo_id
        JOIN member AS m
        ON mp.member_id = m.member_id
        WHERE mp.status = 'Active'";
$res = mysqli_query($conn, $sql);
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  Generated by <?= $_SESSION["admin_id"] ?>
  <?php 
  if($res) {
    if(mysqli_num_rows($res) > 0) {
  ?>
  <table>
    <thead>
      <tr>
        <th>Member ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Promo Name</th>
        <th>Date Availed</th>
      </tr>
    </thead>
    <tbody>
    <?php 
      while($row = mysqli_fetch_assoc($res)) {
      ?>
        <tr>
          <td><?= $row["member_id"] ?></td>
          <td><?= $row["first_name"] ?></td>
          <td><?= $row["last_name"] ?></td>
          <td><?= $row["promo_name"] ?></td>
          <td><?= date("F d, Y", strtotime($row["date_added"])) ?></td>
        </tr>
      <?php
      }
    ?>
    </tbody>
  </table>
  <?php 
    } else {
      echo "Empty";
    }
  } else {
    echo mysqli_error($conn);
  }
  ?>
</body>
</html>